#!/usr/bin/env bash
# set -eux

# colors
black='\033[0;30m'
dark_gray='\033[1;30m'
light_gray='\033[0;37m'
blue='\033[0;34m'
light_blue='\033[1;34m'
green='\033[0;32m'
light_green='\033[1;32m'
cyan='\033[0;36m'
light_cyan='\033[1;36m'
red='\033[0;31m'
light_red='\033[1;31m'
purple='\033[0;35m'
light_purple='\033[1;35m'
brown='\033[0;33m'
yellow='\033[1;33m'
white='\033[1;37m'
default_color='\033[00m'
red_bold='\033[01;31m'
endc='\033[0m'
# colors

# print information
printInfo(){
	printf "$light_green[+]__malloc_hook_offset :$endc$red_bold 0x%x$endc\n" $1
	printf "$light_green[+]main_arena_offset :$endc$red_bold 0x%x$endc\n" $2
	exit
}

info=$(file $1)
is32=1
is64_0x10=1
if [[ "$info" =~ "32-bit" ]]
then
	is32=1
fi

if [[ "$info" =~ "64-bit" ]] && [[ "$info" =~ "GNU/Linux" ]]
then
	is32=0
	is640_x10=1
fi

if [[ "$info" =~ "64-bit" ]] && [[ "$info" =~ "SYSV" ]]
then
	is32=0
	is640_x10=0
fi

mallocHook=$(objdump -j .data -d $1|grep malloc_hook |cut -d " " -f 1)
# echo $mallocHook
let mallocHook=16#$mallocHook
# printf "$light_green[+]__malloc_hook_offset :$endc$red_bold 0x%x$endc\n" $mallocHook

if [ $is32 -eq 1 ]
then
	let mainArena=($mallocHook+0x18)
	printInfo $mallocHook $mainArena
fi

if [ $is64_0x10 -eq 1 ] && [ $is32 -eq 0 ]
then
	let mainArena=($mallocHook+0x10)
	printInfo $mallocHook $mainArena
fi

if [ $is64_0x10 -eq 0 ] && [ $is32 -eq 0 ]
then
	let mainArena=($mallocHook+0x20)
	printInfo $mallocHook $mainArena
fi
# printf "$light_green[+]main_arena_offset :$endc$red_bold 0x%x$endc\n" $mainArena

